"""add scoring_method column

Revision ID: 28f2f3a91c05
Revises: 2cea1f560227
Create Date: 2026-07-20 06:16:57.671934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f2f3a91c05'
down_revision: Union[str, None] = '2cea1f560227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust_score_logs', sa.Column('scoring_method', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trust_score_logs', 'scoring_method')
    # ### end Alembic commands ###
