"""add trust_score_logs table

Revision ID: 2cea1f560227
Revises: 
Create Date: 2026-07-18 18:28:47.240291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cea1f560227'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_score_logs',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('agreement_score', sa.Float(), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('contradiction_score', sa.Float(), nullable=False),
    sa.Column('source_count_score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('distinct_source_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_method', sa.String(length=20), nullable=False),
    sa.Column('labeling_method', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_score_logs')
    # ### end Alembic commands ###
